; Programa que dibuja un cuadrado rojo (asteroide) de 8x8 pixeles.
.ORIG x3000
; R4 contador de columnas
; R5 contador de filas
LD R0, VERDE
LD R2, ROJO   ; color
LD R3, INICIO ; posición asteroide

AND R1, R1, #0
ADD R1, R1, #10
MAIN_LOOP
	LD R4, MEDIDAS_ASTEROIDE
	JSR DIBUJAR_ASTEROIDE
	LD R4, MEDIDAS_ASTEROIDE
	JSR WAIT
	LD R4, MEDIDAS_ASTEROIDE
	;JSR BORRAR_ASTEROIDE
	LD R6, INCREMENTO
	ADD R3, R3, R6
	ADD R1, R1, #-1
	BRp MAIN_LOOP
	HALT

DIBUJAR_ASTEROIDE
    LD R2, ROJO
    LD R6, DESPLAZAMIENTO_FILA ; DESPLAZAMIENTO_FILA
	LD R5, MEDIDAS_ASTEROIDE
	DIBUJAR_HORIZONTAL
		STR R2, R3, #0
		ADD R3, R3, #1
		ADD R5, R5, #-1
		BRp DIBUJAR_HORIZONTAL
	ADD R3, R3, R6  
	ADD R4, R4, #-1
	BRp DIBUJAR_ASTEROIDE
	RET

WAIT
    LD R5, FINAL
	WAIT_LOOP
		ADD R5, R5, #-1
		BRp WAIT_LOOP
	RET

;BORRAR_ASTEROIDE
;    LD R2, BLACK
;    LD R6, DESPLAZAMIENTO_FILA ; 120
;    LD R5, MEDIDAS_ASTEROIDE
;	DIBUJAR_HORIZONTAL_1
;		STR R2, R3, #0
;		ADD R3, R3, #1
;		ADD R5, R5, #-1
;		BRp DIBUJAR_HORIZONTAL_1
;	ADD R3, R3, R6               
;	ADD R4, R4, #-1
;	BRp BORRAR_ASTEROIDE
;	RET

HALT

INICIO .FILL xC078	; xC03C
ROJO .FILL x7C00	; x7C00
FINAL .FILL #15872 ; cantidad total de pixeles
RESTA .FILL #-128
SUMA .FILL #128
IR_1ER_FILA .FILL #-1024 
IR_ULT_FILA .FILL #1024
DESPLAZAMIENTO_FILA .FILL #120
MEDIDAS_ASTEROIDE .FILL #8
INCREMENTO .FILL #-897
DELAY .FILL 8000
BLACK .FILL x0000
VERDE .FILL x03E0
GUARDAR_R3 .BLKW 1
.END
