; Programa que dibuja un cuadrado rojo (asteroide) de 8x8 pixeles.
.ORIG x3000
; R4 contador de columnas
; R5 contador de filas
LD R0, FINAL 
LD R2, ROJO   ; color
LD R3, INICIO ; posición asteroide

AND R1, R1, #0
ADD R1, R1, #3
LD R4, MEDIDAS_ASTEROIDE
MAIN_LOOP
	LD R6, INCREMENTO
	JSR DIBUJAR_ASTEROIDE
	JSR WAIT
	JSR BORRAR_ASTEROIDE
	ADD R3, R3, R6
	ADD R1, R1, #-1
	BRp MAIN_LOOP


LD R4, MEDIDAS_ASTEROIDE
DIBUJAR_ASTEROIDE
    LD R2, ROJO
    LD R6, DESPLAZAMIENTO_FILA ; 120
	LD R5, MEDIDAS_ASTEROIDE
	DIBUJAR_HORIZONTAL
		STR R2, R3, #0
		ADD R3, R3, #1
		ADD R5, R5, #-1
		BRp DIBUJAR_HORIZONTAL
	ADD R3, R3, R6  
	ADD R4, R4, #-1
	BRp DIBUJAR_ASTEROIDE

WAIT
    LD R5, DELAY
	WAIT_LOOP
		ADD R5, R5, #-1
		BRp WAIT_LOOP


LD R4, MEDIDAS_ASTEROIDE
BORRAR_ASTEROIDE
    LD R2, BLACK
    LD R6, DESPLAZAMIENTO_FILA ; 120
    LD R5, MEDIDAS_ASTEROIDE
	DIBUJAR_HORIZONTAL_1
		STR R2, R3, #0
		ADD R3, R3, #1
		ADD R5, R5, #-1
		BRp DIBUJAR_HORIZONTAL_1
	ADD R3, R3, R6               
	ADD R4, R4, #-1
	BRp BORRAR_ASTEROIDE

HALT

INICIO .FILL xC03C
ROJO .FILL x7C00
FINAL .FILL #15872 ; cantidad total de pixeles
RESTA .FILL #-128
SUMA .FILL #128
IR_1ER_FILA .FILL #-1024 
IR_ULT_FILA .FILL #1024
DESPLAZAMIENTO_FILA .FILL #120
MEDIDAS_ASTEROIDE .FILL #8
INCREMENTO .FILL #79
DELAY .FILL 4096
BLACK .FILL x0000
VERDE .FILL x03E0
.END
