.ORIG x3000

LD R0, FINAL
LD R1, RESTA
LD R2, ROJO
LD R3, INICIO
LD R4, SUMA
LD R5, DELAY
LD R6, BLACK

MAIN_LOOP
    JSR CLEAR_SCREEN
    JSR LOOP_J
    JSR WAIT
    ADD R0, R0, R1 ; FINAL, FINAL, RESTA
    BRp MAIN_LOOP
    HALT
    

CLEAR_SCREEN
    ADD R3, R3, R1 ; INICIO, INICIO, RESTA
    STR R6, R3, #0 ; NEGRO, INICIO
    ADD R3, R3, R4 ; INICIO, INICIO, SUMA
    RET

LOOP_J
    
    STR R2, R3, #0 ; ROJO, INICIO
    ADD R3, R3, R4 ; INICIO, INICIO, SUMA
    ;ADD R0, R0, R1 ; FINAL, FINAL, RESTA
    ;BRp MAIN_LOOP
    RET

WAIT
    LD R5, DELAY
        WAIT_LOOP
            ADD R5, R5, #-1
            BRzp WAIT_LOOP 
    RET


HALT


INICIO .FILL xC040
ROJO .FILL x7C00
FINAL .FILL #15872
RESTA .FILL #-128
SUMA .FILL #128
DELAY .FILL 4096
BLACK .FILL x0000
.END